const h = require('./helpers');

function buildPart2() {
  const c = [];

  // PART II OPENER
  c.push(h.pageBreak());
  c.push(h.spacer(600));
  c.push(h.sectionTitle('🔵 PART II'));
  c.push(h.centeredText('UNDERSTANDING', 36, true, '5A4A7A'));
  c.push(h.spacer(200));
  c.push(h.epigraph('The world doesn’t hide its rules.'));
  c.push(h.epigraph('It waits for you to learn how to read them.'));
  c.push(h.pageBreak());

  // CH 6
  const ch6 = [
    'Astra didn’t look for it when she entered the room.',
    'Not this time.',
    'She didn’t slow down or scan the floor, didn’t watch the walls or the edges of light. She just walked in, took her seat, opened her notebook, and waited.',
    'If it followed rules, she reasoned, then it didn’t need her to chase it. It would happen when it was supposed to.',
    'The classroom filled with quiet movement. Pages turned. Chairs shifted. Soft conversations started and stopped in uneven rhythm.',
    'Then she felt it.',
    'Not in front of her, and not where she expected.',
    'Behind her.',
    'Astra turned her head slightly—not fully, just enough to let her view slide across the rows of desks behind her. There, in the middle of the movement, something paused.',
    'Not the whole room.',
    'Just one motion.',
    'A hand lifting a pen stopped for a fraction of a second longer than it should have.',
    'She leaned forward slightly, just enough to bring the desk in front of her into clearer view. A notebook lay open on it, unlike the others around it. There were no half-written lines, no crossed-out words, no loose thoughts pressed into the page.',
    'Everything was structured.',
    'Clean diagrams. Thin lines connecting points across the paper. Small symbols repeated in careful patterns. Precise—too precise to be casual note-taking.',
    'Astra’s breathing slowed.',
    'She hadn’t drawn anything like that. She hadn’t shown anyone what she’d seen. And yet the shapes, while not identical, felt connected in a way she couldn’t ignore.',
    'Before she could stop herself, she spoke.',
    '“Where did you get that?”',
    'The pen stopped.',
    'Slowly, the hand lowered. Then the girl turned—not quickly, not with surprise, but calmly, as if this interruption had been expected, just not scheduled.',
    'Her gaze settled on Astra without hesitation. Focused. Balanced.',
    '“What?” she asked.',
    'Her voice wasn’t defensive or confused. It was simply quiet.',
    '“The… pattern,” Astra said.',
    'The girl’s eyes flickered once—briefly—down to the page, then back to Astra.',
    '“You can see it,” the girl said.',
    'It wasn’t a question.',
    'Something shifted in Astra’s chest. “Yes,” she replied carefully.',
    '“If you look at it directly,” she said quietly, “it disappears faster.”',
    'Astra blinked. “That’s exactly what happens,” she said, the words coming out faster than she meant them to.',
    '“Then don’t look directly.”',
    '“And it stays longer,” Astra added.',
    'For a brief moment the light above them shifted again. Astra saw it. This time, Lumi did too.',
    'Neither of them spoke. Neither of them moved.',
    'The moment held just long enough.',
    'Then everything aligned again. Perfect. Too perfect.',
    'Astra exhaled slowly. “I thought it was just me.”',
    'Lumi shook her head. “No. It’s just… not everyone.”',
    'Astra glanced around the room. No one else had stopped or reacted.',
    'She looked back at Lumi, and for the first time since this had started, the pattern didn’t feel like something she had to chase. It felt like something that could be understood—not yet, but eventually.',
    'Lumi tapped the notebook once more. “You should write it down.”',
    '“It disappears too fast,” Astra said.',
    '“Yes,” Lumi replied. “That’s the point.”',
    'Astra opened her notebook. The same words were still there.',
    'Something is not right.',
    'She added another line.',
    'It repeats.',
    'After a moment, she wrote one more.',
    'And someone else can see it too.',
    'She looked up.',
    'Lumi nodded once. “Good.”',
    'Outside the window, the light shifted again—softly, almost invisibly.',
    'This time, they were both watching.'
  ];
  h.chapterBlock(6, 'Lumi', '🌙 first understanding', ch6).forEach(b => c.push(b));

  // CH 7
  const ch7 = [
    'Astra didn’t notice it at first, and that was the strange part. Lately she noticed almost everything.',
    'The classroom felt ordinary—almost aggressively ordinary. Chairs scraped lightly against the floor, voices overlapped in uneven layers, and pages turned with the same soft rhythm they always had.',
    'She picked up her pencil, paused, and then wrote carefully: It follows something. She stared at the words for a moment before adding another line beneath them: I just don’t know what.',
    'Then she stopped.',
    'The next page wasn’t empty. It should have been—she was certain she hadn’t written anything there. And yet, in the centre of the page, faint enough to miss unless you were paying close attention, something rested.',
    'Not words.',
    'Lines.',
    'Astra leaned closer. They weren’t drawn, and they weren’t pressed into the paper. She couldn’t feel them or trace them. But they were there all the same.',
    'She blinked.',
    'They vanished, leaving the page completely blank again.',
    'Astra remained still. She didn’t turn away or close the notebook, didn’t move her hand or change her posture. After a moment she whispered, very quietly, “Okay.”',
    'She tilted her head slightly, adjusting the angle of her view without leaning in.',
    'The lines returned.',
    'They were fainter this time, but clearer in structure. They weren’t random. They never were. Curves met angles, points aligned with nothing visible, forming something deliberate—something closer to a structure than a drawing.',
    'The bracelet at her wrist pulsed softly. Astra froze. She hadn’t touched it or triggered anything, and yet it responded.',
    '“You’re the same,” she whispered. “Just in a different place.”',
    'The pattern flickered, as if acknowledging her.',
    '“Astra?”',
    'She looked up. The teacher stood at the front of the room.',
    '“Are you following?”',
    'Astra blinked once and nodded. “Yeah.”',
    'Her voice sounded normal. Calm.',
    'She looked back down. The page was blank again. Completely.',
    'She frowned and flipped back. Her writing on the previous page remained clear and unchanged. When she turned forward again, the page was empty once more.',
    'Astra leaned back slightly, thinking. Not random. Not simple disappearance. Timing, angle, focus—the same rule as before.',
    'She turned the page again. Still nothing.',
    'Then she adjusted her posture and relaxed her focus, letting her gaze soften instead of fixing directly on the page.',
    'The lines returned.',
    'Stronger this time.',
    'Almost without thinking, she began to draw, tracing what she believed she saw.',
    'The instant her pencil touched the paper, the lines vanished.',
    '“That’s not it,” she whispered.',
    'The real pattern hadn’t been on the page. It had existed somewhere just before the page became something else.',
    '“You don’t want to be copied,” she said quietly.',
    '“You’re not something I draw,” she said. “You’re something I read.”',
    'The bracelet dimmed.',
    'Astra closed the notebook on purpose this time.',
    '“You don’t show up when I try,” she whispered. “You show up when I see you properly.”',
    'The bracelet pulsed once more, soft and steady.',
    '“I’ll learn how to read you,” she said quietly.',
    'No one noticed anything. The light didn’t change. The room remained exactly as it had been.',
    'But the space felt aligned, as if something had settled into the right place.',
    'And somewhere beyond what could be drawn, the pattern waited—ready to be understood.'
  ];
  h.chapterBlock(7, 'The Notebook That Doesn’t Match', '🌙 second understanding', ch7).forEach(b => c.push(b));

  // CH 8
  c.push(h.pageBreak());
  c.push(h.chapterTitle('Chapter 8 — There Are Rules'));
  c.push(h.chapterSubtitle('🌙 third understanding'));
  c.push(h.rule());
  const ch8paras = [
    'The Academy had rules. Everyone knew that.',
    'Rules about where to walk, when to speak, how to move through corridors that had been designed to hold more than footsteps. Rules about which doors to open and which to leave closed. Rules that felt ordinary until you started to notice that some of them weren’t about behaviour at all.',
    'They were about perception.',
    'Astra had been thinking about this since the notebook. Not the lines themselves—those had faded, as they always did—but the principle behind them. The pattern didn’t respond to force. It didn’t respond to attention that was too direct, too demanding, too certain of what it expected to find.',
    'It responded to something else.',
    'She sat in the library that afternoon, her notebook open but untouched, and tried to name it.',
    'Lumi arrived without announcement, sliding into the seat across from her with the quiet efficiency of someone who had already decided where they were going before they stood up.',
    '“You’re thinking about the rules,” Lumi said.',
    'It wasn’t a question. Astra had noticed that about her—Lumi rarely asked questions she already knew the shape of.',
    '“Yes,” Astra said. “But I can’t name them yet.”',
    'Lumi set her notebook on the table. It was open to a page dense with small, careful writing—observations, Astra realised. Not theories. Observations.',
    '“Rule one,” Lumi said, without preamble. “It doesn’t appear when you look directly.”',
    '“Rule two,” Astra continued, understanding immediately. “It disappears when you try to record it.”',
    '“Rule three.” Lumi tapped the page. “It repeats. Same behaviour, different surfaces.”',
    'Astra looked at her. “You’ve been making a list.”',
    '“I’ve been making observations,” Lumi corrected. “The list is a consequence.”',
    'Astra almost smiled. “What’s the difference?”',
    '“A list assumes you know what you’re looking for,” Lumi said. “Observations don’t.”',
    'That landed cleanly. Astra looked down at her own notebook—at the three lines she’d written days ago, still unchanged.',
    'Something is not right. It repeats. And someone else can see it too.',
    '“Those aren’t rules,” she said slowly. “Those are observations.”',
    '“Yes,” Lumi said. “Which means you’ve been doing it correctly.”',
    'The library was quiet around them—the particular quiet of a room that held more than books, where the air felt slightly denser than it should, as if the space itself was paying attention.',
    '“There’s a fourth rule,” Astra said after a moment.',
    'Lumi looked up.',
    '“It responds differently depending on who’s watching,” Astra said. “Or how many.”',
    'Lumi was quiet for a moment. Then she wrote something in her notebook—carefully, precisely—and turned it so Astra could read it.',
    'Rule 4: The system is not independent of the observer.',
    'Astra read it twice. “That changes everything.”',
    '“Yes,” Lumi said. “It does.”',
    'Outside the library window, the afternoon light shifted—barely, almost imperceptibly—and for just a moment, the edge of the glass held something that wasn’t quite a reflection.',
    'Both of them saw it.',
    'Neither of them looked away.'
  ];
  ch8paras.forEach(p => c.push(h.bodyPara(p, true)));
  c.push(h.italicPara('✦'));

  // CH 9
  const ch9 = [
    'Astra noticed it before she noticed the pattern.',
    'That was the difference this time. It wasn’t quiet and didn’t ease itself into her attention the way the others had. It cut straight through the moment.',
    '“Wow—okay. That was definitely weird.”',
    'Astra blinked. Lumi did too. They both turned.',
    'A girl stood a few steps away, half leaning against a desk she hadn’t been sitting at before. She looked at them, then past them, then back again, as if she were tracking something invisible but not staying still long enough to follow it properly.',
    '“Did you just see that?” she asked.',
    'Astra hesitated. Lumi didn’t.',
    '“What did you see?” Lumi asked.',
    'The girl gestured vaguely, not pointing at the window or the wall or anything specific. “Something shifted,” she said. “That thing the space does.”',
    'Astra felt the bracelet pulse—short and sharp, different from before. Unsteady.',
    '“You mean a delay?” Astra asked carefully.',
    'The girl frowned. “No. I mean… kind of?” She straightened and took a step closer. “I don’t know what you’d call it. It just happened all at once.”',
    '“That’s not how it behaves,” Lumi said quietly.',
    'Astra glanced at her. Behaves.',
    'The girl looked between them. “What do you mean, behaves?”',
    'Astra paused, then said, “It follows rules.”',
    'The girl blinked. “Rules?”',
    'She wasn’t dismissive. Just curious.',
    '“Yeah,” Astra said. “It doesn’t just happen. There’s a pattern.”',
    'The girl’s expression shifted more quickly than Astra could fully read. “A pattern?” she repeated, and smiled slightly. “Okay. That’s better.”',
    '“Better how?” Astra asked.',
    'Instead of answering, the girl stepped past them toward the window. She didn’t slow down or adjust her angle, and she didn’t seem to be trying. She simply moved into the light as if it were part of the room.',
    'For a moment everything shifted.',
    'But not the way Astra expected.',
    'It didn’t delay or misalign. It compressed. Several moments tried to exist at the same time.',
    'The correction still came, but faster and messier, like it hadn’t settled properly.',
    'The girl stepped back out of the light, laughing quietly under her breath. “Okay, yeah. You saw that, right?”',
    'Astra nodded slowly. Lumi didn’t answer.',
    '“That wasn’t before correction,” Lumi said. “That was interference.”',
    'The word felt heavier. Less clean.',
    'Astra looked at the girl again. “You’re changing it,” she said.',
    '“I’m not trying to,” the girl replied. “It just happens when I move through it.”',
    'The bracelet flickered—not pulsed this time. Uncertain.',
    '“That’s new,” Astra whispered.',
    'Lumi nodded slowly. “Different input,” she said. “Same system.”',
    'The girl stepped back toward them. “You two are taking this very seriously.”',
    '“Yes,” Astra said.',
    'The girl smiled. “Good. Because it’s actually kind of fun.”',
    '“It isn’t random,” Lumi said.',
    '“I didn’t say it was,” the girl replied. “It’s just not fixed either.”',
    '“What do you mean?” Astra asked.',
    'The girl finally focused fully on them. “Your version,” she said, nodding between Astra and Lumi, “feels like you’re trying to understand it. You,” she added to Astra, “wait for it. And you,” she said to Lumi, “break it into rules.”',
    '“That’s accurate,” Lumi said.',
    'The girl nodded. “Yeah. I don’t do either.”',
    '“So what do you do?” Astra asked.',
    'The girl thought for a moment. “I follow it.”',
    '“Follow?” Lumi asked.',
    '“Not like chasing it,” the girl said. “More like moving with it.”',
    'She stepped sideways. The light shifted again, but this time it didn’t break or correct itself. It flowed, changing softly before settling.',
    'Astra felt her breathing slow.',
    'That was new.',
    '“I didn’t try to fix anything,” the girl said. “I just didn’t resist it.”',
    '“That isn’t predictable,” Lumi said.',
    '“No,” the girl agreed. “But it works.”',
    'Astra looked between them. Pattern. Rules. Flow. Different approaches, connected by the same thing.',
    'The bracelet flickered, then pulsed, then steadied.',
    '“You can see that too?” Astra asked the girl. “The bracelet?”',
    '“Not clearly,” she replied. “But I can feel when something changes around you.”',
    '“Same system,” Lumi said, more certain now.',
    'The girl stepped back slightly. “I should probably introduce myself.”',
    'She hesitated just a moment. “I’m Nela.”',
    '“Astra,” Astra said.',
    '“Lumi.”',
    'Nela smiled. “Yeah. That fits.”',
    '“What now?” she asked.',
    '“We learn the rules,” Astra replied.',
    '“And test consistency,” Lumi added.',
    'Nela tilted her head. “Or we see where it goes.”',
    'Astra almost smiled. Not because one of them was right, but because all of them were, in different ways.',
    'The light near the window shifted again.',
    'This time Astra watched. Lumi analysed. Nela stepped forward.',
    'The system reacted—not perfectly, not cleanly, but more than before.',
    '“We’re not supposed to do this alone,” Astra said quietly.',
    'Lumi didn’t argue. Nela smiled. “Good.”',
    'Because beneath the surface of everything that still looked ordinary, something was changing—not reacting to one of them, but to all three together.'
  ];
  h.chapterBlock(9, 'Nela', '🌙 fourth understanding', ch9).forEach(b => c.push(b));

  // CH 10
  const ch10 = [
    'Astra noticed the change immediately.',
    'Not the pattern itself, but the way it felt. Before, the system had been something she watched from a distance, something she adjusted for and tried to understand. Now it felt aware—still not alive, not thinking, but responsive in a way it hadn’t been before.',
    'She stood near the window again, Lumi beside her and Nela a little ahead. Nela was already moving, already testing something without announcing it, as if motion came more naturally to her than caution.',
    '“Try the same thing,” Lumi said quietly. Her tone was calm, focused.',
    'Nela glanced back at them with a small smile. “Which version?”',
    'Astra almost smiled too. There were versions now—different ways of interacting, different ways of seeing.',
    '“Not forcing,” Astra said.',
    '“And not analysing first,” Nela added.',
    'Lumi hesitated for a moment, then nodded. “Fine. Just observe.”',
    'Nela stepped forward. Not slowly, but not recklessly either. There was a rhythm to her movement that Astra could feel as much as see.',
    'Nela moved into the light.',
    'Nothing broke. Nothing lagged. For a moment everything held exactly as it was.',
    'Astra frowned slightly. “That’s new.”',
    '“Wait,” Lumi said.',
    'Astra felt it then—not in the light itself, but in the space around it. Something had shifted underneath, deeper than the surface.',
    '“Don’t move,” Astra said.',
    'Nela froze mid-step, holding herself completely still. The room remained normal. The light didn’t change. But something between the three of them moved.',
    'Astra softened her focus, not on the floor and not on Nela, but between them.',
    'For the first time, the pattern didn’t flicker.',
    'It formed.',
    'Clearer than before. Stronger. Stable.',
    '“It’s staying,” Astra said.',
    'Lumi stepped closer, careful not to disturb the alignment. “I see it,” she said, without hesitation.',
    'Nela didn’t turn. “Okay,” she said quietly. “That definitely feels different.”',
    '“It isn’t correcting itself,” Astra said. “It’s holding.”',
    'Lumi’s expression shifted as she processed that. “That shouldn’t happen,” she said. “But it is.”',
    'Astra took a small step forward. The pattern responded—not by disappearing, but by adjusting, as if it registered her movement.',
    'Astra froze. “It moved because of me.”',
    '“No,” Lumi said. “Because of us.”',
    'A short silence followed.',
    'Astra looked at Nela, still standing in the light. “You’re anchoring it,” she said.',
    '“I’m what?” Nela asked, blinking.',
    '“Not on purpose,” Astra said quickly. “But something about how you’re standing—”',
    '“It isn’t resisting,” Lumi finished.',
    'Nela let out a slow breath. “So I don’t move.”',
    '“For now,” Astra said.',
    '“For now,” Nela agreed.',
    'Astra adjusted her gaze again, not forcing anything, just aligning. The pattern became clearer, its connections revealing themselves. It wasn’t random and it wasn’t incomplete. It was structured.',
    'Astra lifted her hand slightly, not to touch, just closer. The pattern shifted softly, like something opening just enough to be noticed.',
    '“It changed,” Astra said.',
    'Lumi moved closer. “What triggered it?”',
    'Astra didn’t answer right away. She felt it more than she understood it. “Position,” she said slowly. “And attention.”',
    '“That sounds right,” Nela said. “It feels like it’s waiting.”',
    'Waiting.',
    'That mattered.',
    'Astra focused again, not harder, just more clearly. The pattern shifted once more, becoming more defined. It wasn’t only lines now. There was direction, a sense of flow.',
    '“It isn’t just a structure,” Astra said. “It’s guiding something.”',
    '“Guiding what?” Lumi asked.',
    'Astra hesitated, then said quietly, “Us.”',
    'The bracelet pulsed, this time strong and certain. All three of them felt it.',
    '“You see different parts of it,” Astra said. She looked at Lumi. “You understand it.” Then at Nela. “You move with it.” She paused. “And I see when it changes.”',
    'She looked back at the pattern. “Together, we can make it react.”',
    'The light bent slightly. The pattern shifted again and held, present in a way it hadn’t been before.',
    'Waiting.',
    'Not for one of them.',
    'For all of them.',
    'Together.'
  ];
  h.chapterBlock(10, '“Don’t Ask. Just Hold This.”', '🌙 fifth understanding', ch10).forEach(b => c.push(b));

  return c;
}

module.exports = { buildPart2 };