const h = require('./helpers');

function buildPart3() {
  const c = [];

  // PART III OPENER
  c.push(h.pageBreak());
  c.push(h.spacer(600));
  c.push(h.sectionTitle('🟡 PART III'));
  c.push(h.centeredText('CONNECTING', 36, true, '5A4A7A'));
  c.push(h.spacer(200));
  c.push(h.epigraph('A symbol is not a sign.'));
  c.push(h.epigraph('It is a beginning.'));
  c.push(h.pageBreak());

  // CH 11
  const ch11 = [
    'Astra didn’t go looking for it, and that was the first real difference.',
    'Before, she had waited for the pattern to appear, watching and adjusting herself to whatever the space seemed to require. Now she simply walked, trusting the awareness she had learned rather than searching for a sign.',
    'The corridor felt exactly the way it always had. Light stretched across the floor in long, soft bands, and the sound of movement echoed faintly from somewhere beyond view. Nothing about it looked wrong. And yet something underneath it wasn’t settled.',
    'Astra slowed her steps, not suddenly and not enough to draw attention. Just enough to stay with the feeling.',
    'Lumi noticed immediately. “You felt that,” she said quietly.',
    '“Yes,” Astra replied.',
    'Nela kept walking. She moved ahead of them, then turned once, scanning the space the way she did when she sensed a direction rather than a place.',
    '“Okay,” Nela said. “That’s definitely something.”',
    'Astra took another step forward, not toward anything specific but toward the sensation itself. The space shifted slightly. Lumi adjusted her posture, already observing the change before she could fully describe it.',
    'Astra softened her focus, letting her attention hover just beyond the surfaces around them. She wasn’t looking directly for anything now; she was letting herself stay open to what was forming.',
    'That was when she saw it.',
    'It wasn’t a flicker or a reflection. It was a shape, still faint and still unstable, but holding its position longer than it ever had before.',
    'Astra didn’t speak right away. She stayed with it, letting the moment settle. Then she said quietly, “It’s there.”',
    'Lumi stepped closer, careful not to disturb the alignment. “Where?” she asked.',
    'Astra didn’t point. Instead, she shifted her stance slightly, changing the angle just enough to let Lumi follow what she was seeing.',
    '“There,” Astra said again.',
    'Lumi paused. Her expression changed, just subtly. “I think I can see it,” she said, then stopped. “That’s new.”',
    '“Yes,” Astra agreed.',
    '“This time, stay where you are,” Astra replied to Nela.',
    'Nela hesitated, then nodded and didn’t move.',
    'The air between the three of them felt different, not quiet and not empty, but structured, as if the space itself had decided to hold.',
    'Astra adjusted her focus again. The lines within the shape became clearer. They weren’t separate or scattered; they were connected, forming something that kept its structure longer than anything she had seen before.',
    '“It’s not breaking,” Astra whispered.',
    'Lumi shifted one step to the side. The shape changed, not disappearing but adjusting.',
    '“Position matters,” Lumi said.',
    'Nela moved forward just slightly. The pattern reacted again, expanding instead of collapsing.',
    'Astra felt it immediately. “Stop there,” she said.',
    'Nela froze, completely still.',
    'For a brief moment, everything aligned.',
    'Then the structure completed itself—not fully and not permanently, but enough that Astra recognised it as something whole rather than a fragment.',
    'A symbol.',
    'Astra’s breathing slowed. “It’s the same,” she said quietly. “The same as before.”',
    'Not the flicker or the broken trace, but the complete form.',
    'Lumi stared at it. This time she didn’t reach for her notebook or try to record it. “For the first time,” she said carefully, “I can see the structure without losing it.”',
    'Nela leaned slightly into the space without moving closer. “That doesn’t feel like a glitch,” she said. “It feels like it’s waiting.”',
    'The word settled naturally. Astra understood it now. This wasn’t something breaking or misfiring; it was something present and aware of their positions.',
    'Astra felt the realisation before she said it. “It needs all of us.”',
    'Nela smiled faintly. “Well,” she said, “that’s new.”',
    'Lumi didn’t smile, but her posture eased. “It’s consistent,” she said.',
    'Astra almost laughed, not because the moment was amusing, but because it finally made sense.',
    '“That wasn’t a glitch,” Astra said.',
    'Lumi shook her head. “No. It’s a mark.”',
    '“A mark of what?” Nela asked.',
    '“Of connection,” Astra said.',
    'They didn’t explain it any further. They didn’t need to.',
    'Astra took a small step forward, not chasing anything and not forcing the space to change. For the first time since this had started, she wasn’t questioning whether what she had seen was real.',
    'She knew it was.',
    'And she knew she wasn’t alone anymore.'
  ];
  h.chapterBlock(11, 'The First Symbol', '🌙 first connection', ch11).forEach(b => c.push(b));

  // CH 12
  const ch12 = [
    'Astra didn’t expect it to come back so quickly, but she did expect something. That was the difference now. She wasn’t waiting to see whether it would appear; she was waiting to understand it.',
    'The corridor was quiet again. Not empty—never empty anymore—but layered, as if sound, movement, and light were all resting on different levels of the same space.',
    '“Are we doing this again?” Nela asked.',
    'Astra didn’t answer immediately. She was listening—not to sound or movement, but to what sat beneath them.',
    '“Yes,” she said finally. “But not the same way.”',
    'Lumi nodded once. “It has to change,” she said. “Repeating didn’t work.”',
    '“Good,” Nela replied, pushing herself away from the wall. “Because I wasn’t planning to.”',
    'Astra stepped forward, not toward the wall but toward the sensation itself. At the edge of her perception, the space shifted. It was soft and subtle, but clear enough now for her to recognise it.',
    '“It’s starting,” Astra whispered.',
    'Lumi adjusted her stance without being told. “Angle first,” she said.',
    '“Then timing,” Astra agreed.',
    'Nela didn’t ask where to stand. She moved into a position that felt right, even if she couldn’t explain why.',
    'The moment settled.',
    'The symbol formed—not struggling, not flickering, but arranging itself smoothly.',
    '“It’s the same,” she said quietly, though her voice carried less uncertainty than before.',
    'Lumi leaned in slightly, careful not to disturb the balance. “I can see the structure again,” she said. “More clearly.”',
    '“I still don’t see it like you do,” Nela said, tilting her head.',
    'Astra glanced at her. “But you feel it.”',
    'Nela paused, then nodded. “Yeah. I do.”',
    'The silence that followed wasn’t empty. It was thoughtful. The symbol held longer than it ever had, not fading or shifting, as if it were waiting.',
    'Astra sensed the change, not in the shape itself but in how she was looking at it. “It isn’t just a shape,” she said.',
    'Lumi’s gaze sharpened. “No,” she said slowly. “It’s organised.”',
    '“More than that,” Astra replied, hesitating to phrase it too quickly. “It’s saying something.”',
    'Nela raised an eyebrow. “That’s new.”',
    'Lumi studied the structure without trying to pull it apart. “Not saying,” she said after a moment. “Encoding.”',
    '“That matters,” Astra said softly.',
    '“If it means something,” Nela said, “how do we read it?”',
    'Astra didn’t answer right away. She didn’t know yet. But she knew where to begin.',
    '“Don’t break it,” she said.',
    'Nela froze. “I wasn’t going to—”',
    '“You were,” Lumi said calmly.',
    'Nela smiled faintly. “Okay. Fair.”',
    'The symbol adjusted again, with more definition than before.',
    '“There,” Astra said. “Did you see that?”',
    '“Yes,” Lumi replied immediately.',
    '“…Not exactly,” Nela said after a pause.',
    '“It’s changing in parts,” Astra said. “Not all at once.”',
    'Lumi shifted to match Astra’s angle. “Segments,” she said.',
    'Nela took a step sideways. The structure reacted again and held—clearer now, brighter, not complete, but intentional.',
    '“It isn’t just showing something,” Astra said quietly. “It’s guiding something.”',
    '“Sequence,” Lumi said.',
    '“Path,” Nela added.',
    'Different words. Same meaning.',
    'The bracelet pulsed, steady and unmistakable. The symbol brightened slightly, as if confirming something.',
    '“If it means something,” Astra said, “it’s not there for us to look at.”',
    '“It’s there to be followed,” Lumi replied.',
    'Nela smiled. “That part I get.”',
    '“We’re not just finding it anymore,” she said. “We’re part of how it works.”',
    'Lumi nodded. “Yes.”',
    'Nela smiled, quieter than usual. “Good,” she said. “Because I don’t think it works without us.”'
  ];
  h.chapterBlock(12, 'If It Means Something…', '🌙 second connection', ch12).forEach(b => c.push(b));

  // CH 13
  const ch13 = [
    'Astra didn’t wait this time, and that was new.',
    '“We try again,” she said.',
    'Lumi looked at her immediately. “Under the same conditions?”',
    'Astra shook her head. “Closer.”',
    'They took their positions. Not exactly the same as before, but not randomly either. Astra moved first. Lumi adjusted after her. Nela stepped into place last.',
    'The space reacted, not immediately, but clearly enough to be felt.',
    '“It’s working,” she said quietly.',
    '“Yes,” Lumi agreed, “but not the same.”',
    '“Feels faster,” Nela said.',
    'Astra nodded. Then she moved—just slightly.',
    'The symbol collapsed.',
    'Gone.',
    '“Okay. That did not work,” Nela said.',
    'Lumi stepped back at once. “You changed position too early,” she said.',
    '“I thought it was stable,” Astra replied.',
    '“It wasn’t,” Lumi said. After a pause, more gently, “Not yet.”',
    'Astra nodded. She wasn’t frustrated. She was adjusting.',
    '“Again,” she said.',
    '“Already?” Nela blinked.',
    '“Yes.”',
    'This time they adjusted before starting. Lumi moved first. “Angle needs to align before formation,” she said.',
    'The symbol formed, but weaker, flickering.',
    '“Stop,” Astra said quickly.',
    'All three froze.',
    'The symbol struggled to hold, then fractured into fragments and disappeared.',
    '“Okay,” Nela muttered. “So not that either.”',
    '“That wasn’t wrong,” Lumi said.',
    '“It was incomplete,” Lumi replied.',
    '“So what’s missing?” Nela asked.',
    'Lumi hesitated. “I don’t know.”',
    'For her, that admission mattered.',
    'Astra noticed. “You don’t have to,” she said quietly.',
    'Lumi looked at her, then nodded, letting the pressure ease.',
    '“Try something different,” Nela suggested.',
    '“This feels too careful,” Nela said.',
    'Astra froze.',
    'That feeling—control—was familiar. She exhaled slowly. “We are.”',
    'Lumi didn’t argue.',
    'Astra stepped back just enough to change the tone of the space. “Again,” she said, but this time her voice was less controlled and more open.',
    'They moved together, not perfectly and not by calculation, but in alignment.',
    'The symbol appeared immediately, clearer than before.',
    '“It’s holding,” Lumi said.',
    'Nela shifted slightly, carefully this time. The symbol didn’t break.',
    'It changed.',
    '“That’s it,” Astra said.',
    '“Yes,” Lumi said. “Because we’re not forcing it.”',
    '“Told you,” Nela said lightly.',
    'Astra leaned forward a fraction. The symbol responded by expanding. The lines stretched and connected further.',
    '“This is different,” Astra said.',
    '“It’s adapting,” Lumi said, stepping closer without disturbing it.',
    'Nela watched the change. “So we’re not just finding the right way,” she said slowly. “We’re helping it change.”',
    '“That might be true,” Astra agreed.',
    'The bracelet on her wrist pulsed, steady and unmistakable.',
    '“Stop,” she whispered.',
    'All three remained still.',
    'The pattern stabilised, brighter for a moment longer than before.',
    'Then it faded gently, as if it had reached its limit.',
    '“That was better,” Nela said.',
    '“Yes,” Lumi agreed.',
    '“We didn’t repeat it,” Astra said.',
    '“No,” Lumi replied. “We adjusted.”',
    '“And we stopped trying to control it,” Nela added.',
    '“That’s the rule,” Astra said quietly. “A new one.”',
    '“We don’t make it happen.”',
    '“We allow it,” Lumi finished.',
    '“That works better,” Nela said.',
    'Astra looked ahead. The corridor felt unchanged, but now it wasn’t empty in the same way. It felt open, as if it were waiting for them to try again.',
    'Only this time, they knew better than to repeat what had already happened.'
  ];
  h.chapterBlock(13, 'Try It Again', '🌙 third connection', ch13).forEach(b => c.push(b));

  // CH 14
  const ch14 = [
    'Astra didn’t say again this time. She didn’t need to. The corridor already felt as if it were waiting.',
    'They stood at the edge of the Portal Corridor, where the light always seemed a little too clean and a little too organised, as if it followed rules that were never said out loud.',
    '“Same approach,” Lumi said quietly. Not the same positions and not the same steps, just the same principle.',
    '“Don’t force it,” Astra added.',
    'Nela lifted both hands, deliberately serious. “I am the picture of not forcing,” she said, then softened. “Just tell me where to stand.”',
    'Astra glanced at her. The fact that Nela asked without joking mattered more than anything else at that moment. Astra didn’t point sharply; she shifted half a step and opened a space beside her.',
    '“Here.”',
    'Nela stepped into it without hesitation, as if the space had been waiting for her.',
    'Lumi didn’t open her notebook. She held it against her chest instead, watching the space itself rather than preparing to write. Astra noticed that too. Lumi wasn’t only analysing anymore. She was learning how to stay present.',
    'The air changed.',
    'It didn’t move or flicker. It simply became more structured.',
    'Astra softened her focus, not looking at the wall or the floor but at the space where things connected. That was where the first lines appeared. They weren’t weak or unstable. They formed with intention.',
    '“It’s earlier,” Lumi whispered.',
    '“Yes,” Astra said.',
    'Nela went completely still.',
    'The shape held longer than before, long enough that holding no longer felt like the wrong word. Then the corridor trembled slightly, as if the building itself had taken a quiet breath in.',
    'Astra felt her bracelet pulse once—steady and calm. Not a warning. Confirmation.',
    '“It’s not just showing something,” Astra said. “It’s asking.”',
    'Lumi’s reply came carefully. “Then we answer.”',
    'Astra didn’t move. She didn’t lean forward or try to trap the moment. She remembered what they had learned already: control broke it, allowing let it form.',
    'The shape brightened slightly, not like a lamp, but like a thought becoming clearer.',
    'Nela shifted her weight a fraction, then froze again. The structure reacted, not by disappearing, but by adjusting.',
    '“It knows we’re here,” Astra said.',
    'Lumi nodded. “Not knows,” she corrected. “Tracks.”',
    'Astra almost smiled. “Fine. It tracks us.”',
    'Then something new happened.',
    'It wasn’t the symbol this time. It was the corridor itself.',
    'A faint line of light appeared along the edge of the wall, thin enough to be missed if you weren’t already watching for it. It connected the structure to something deeper inside the Portal Corridor.',
    'Astra stopped breathing for a moment. Lumi saw it immediately. Nela raised her eyebrows.',
    '“That’s a path,” Nela said quietly.',
    'The shape shifted again. For a moment Astra saw not only a single form, but a relationship—what came before and what might come after.',
    '“If it’s a system,” Lumi murmured.',
    '“Then it has steps,” Astra finished.',
    'The line of light pulsed once, then again, then went still, as if waiting for something precise.',
    'Lumi studied the floor, then the wall, then the air between them. She wasn’t confused. She was choosing what to test without breaking the alignment.',
    '“Something is missing,” she said.',
    'Nela didn’t ask what. She reached into her backpack, not dramatically, but with the ease of someone who suddenly understood why they had brought something along. She pulled out a small prism lens, plain enough to seem unimportant until you paid closer attention.',
    'Lumi instinctively started to say don’t, then stopped herself. “Be careful,” she said instead.',
    '“I will,” Nela replied, and this time she meant it.',
    'Astra held her breath, not out of fear, but because she didn’t want sound to break the moment.',
    'Nela lifted the prism slowly, not toward the structure, but toward the light itself. She didn’t try to see through it, only to shape how the light moved.',
    'The moment the beam divided, Astra felt the response.',
    'The structure didn’t fade. It didn’t resist. It aligned.',
    'The corridor filled with three subtle tones, never bright and never loud. A faint violet edge where Astra stood. A calm blue clarity near Lumi’s steady focus. A warm gold thread where Nela held the lens.',
    'Not as power.',
    'As roles the system could recognise.',
    '“This is it,” Lumi whispered. “This is the language.”',
    'Astra didn’t move. She watched the structure shift and expand, not because it was pushed, but because it was understood.',
    'The line of light along the wall brightened and travelled deeper into the corridor, not like an explosion, but like the building itself had accepted the answer.',
    '“It worked,” Nela said softly.',
    '“It responded,” Lumi corrected.',
    'Astra nodded. “It reacted.”',
    'They stayed where they were, not celebrating and not rushing. They let the system finish doing what it needed to do, because they had learned that it finished best when they didn’t interfere.',
    'The light softened. The structure faded, not as a failure, but as a completed step.',
    'Nela carefully put the prism back into her bag. Lumi exhaled slowly, as if she’d been holding her breath for a long time.',
    'Astra looked at the place where the structure had been and realised she wasn’t afraid of it anymore.',
    'She felt responsible for it.',
    'Not alone.',
    '“This proves it,” Lumi said quietly.',
    '“The system reacts to understanding,” Lumi finished.',
    '“And teamwork,” Nela added with a faint smile.',
    '“And not to force,” Astra said, because that part mattered most.',
    'For the first time, Astra didn’t feel as if she were chasing something hidden.',
    'She felt as if the hidden system had noticed them back.'
  ];
  h.chapterBlock(14, 'It Reacted', '🌙 fourth connection', ch14).forEach(b => c.push(b));

  // CH 15
  const ch15 = [
    'The corridor returned to normal.',
    'Quiet. Still. Unchanged.',
    'Astra didn’t move right away. She knew that if she rushed past the moment, it would slip into memory instead of settling into something real.',
    '“Okay,” Nela said softly.',
    'That was all. No jokes. No exaggeration. Just a shared understanding.',
    'Lumi let out a slow breath. “That was…” she began, then stopped. There wasn’t a word for it yet.',
    '“Yes,” Astra said. She didn’t try to explain either. Explaining would only make it smaller.',
    'They started walking again, not quickly and not slowly, just enough to leave the exact place behind without leaving the moment itself.',
    '“Do you think,” Nela began, then paused, “…that it only works when we’re all there?”',
    '“Yes,” Lumi said immediately. Then, more carefully, “At least for now.”',
    'Astra let that settle. It didn’t feel like a limit. It felt like a truth.',
    '“We didn’t make it happen,” Astra said.',
    '“We aligned,” Lumi replied.',
    '“And then it reacted,” Nela added.',
    'Astra almost smiled. “That’s the part I like.”',
    'They stepped into a quieter space beyond the corridor—not a new location, just one with less noise and movement.',
    'Lumi looked down at her notebook. It was still closed. She didn’t open it.',
    'That mattered.',
    '“You’re not writing it down?” Nela asked.',
    '“No,” Lumi said. After a brief pause, she added, “I remember it.”',
    'Astra looked at her. That was new.',
    '“So what now?” Nela asked.',
    'Astra didn’t answer immediately. This time it wasn’t about the next step. It was about staying with this one.',
    '“We don’t rush it,” she said.',
    '“We understand it,” Lumi added.',
    '“And we try again,” Nela said.',
    'Astra looked at both of them. Something settled—not around her, but inside.',
    '“We only got this far because we were together,” she said.',
    'Lumi didn’t argue. Nela didn’t joke. They both knew it.',
    'After a moment, Nela spoke again, quieter than usual. “I don’t think I could do this alone.”',
    '“You don’t have to,” Astra said.',
    '“None of us do,” Lumi added.',
    'That stayed with them. Not heavy. Just true.',
    'Astra rested her hand lightly on her wrist. The bracelet was calm now, no longer pulsing. But it didn’t feel empty. It felt connected.',
    '“It isn’t reacting to me alone,” Astra said. “It’s reacting to us.”',
    '“That would explain the stability,” Lumi said.',
    'Nela smiled faintly. “So we’re part of the system now?”',
    'Astra hesitated, then said, “I think we always were.”',
    'That settled deeper than anything else had.',
    'They stayed there for a moment longer, not needing to move or prove anything. For the first time, they weren’t trying to reach the system.',
    'They were already part of it.',
    '“We should probably go,” Nela said quietly, though she didn’t move.',
    '“Yeah,” Lumi agreed, also staying where she was.',
    '“Just a second more,” Astra said.',
    'Neither of them argued.',
    'When they finally continued walking, they moved together. Not ahead and not behind. Aligned.',
    'And somewhere beyond what could be seen, the system held—not waiting for one of them, but for all three.',
    '“Before, I always thought I had to figure it out first,” Astra said.',
    '“And now?” Lumi asked.',
    '“Now I think I just need to notice it,” Astra replied, then added, “and trust that we’ll figure it out together.”',
    '“That changes the variables,” Lumi said.',
    '“Or maybe,” Nela added, “it makes them easier.”',
    'Lumi almost corrected that. Almost. Then said, “Maybe both.”',
    '“If we mess it up next time,” Nela said after a moment.',
    '“We will,” Astra replied.',
    '“As long as we’re messing it up together,” Nela said.',
    '“Always,” Astra answered.',
    '“And then it’s not a mistake,” Lumi added softly.',
    'That needed no explanation.',
    'They took a few more steps. For a moment, nothing changed. Then the light ahead of them didn’t quite line up.',
    'Not wrong. Not broken.',
    'Different.',
    'Astra stopped briefly. Lumi noticed. Nela felt it.',
    'They didn’t feel surprised.',
    'They felt ready.',
    '“Next time,” Astra said, “it won’t be the same.”',
    '“It’s not supposed to be,” Lumi replied.',
    '“Good,” Nela said. “Because I think it’s starting to change.”',
    'Astra didn’t answer. She looked ahead, to where the corridor felt just slightly altered.',
    'For the first time, that didn’t feel like something to solve.',
    'It felt like something to step into.'
  ];
  h.chapterBlock(15, 'The Three of Us', '🌙 fifth connection', ch15).forEach(b => c.push(b));

  return c;
}

module.exports = { buildPart3 };