const h = require('./helpers');

function buildPart4() {
  const c = [];

  // PART IV OPENER
  c.push(h.pageBreak());
  c.push(h.spacer(600));
  c.push(h.sectionTitle('🌌 PART IV'));
  c.push(h.centeredText('ACTIVATING', 36, true, '5A4A7A'));
  c.push(h.spacer(200));
  c.push(h.epigraph('The system doesn’t open for those who push.'));
  c.push(h.epigraph('It opens for those who understand.'));
  c.push(h.pageBreak());

  // CH 16
  const ch16 = [
    'Astra noticed it on the third step.',
    'Not the light. Not the air. The distance.',
    'She stepped forward, and the corridor answered with a step that felt longer than it should have been. Not stretched or distorted—just slightly rewritten, as if the space had adjusted its own measurement.',
    'Astra stopped.',
    'Lumi stopped beside her. Nela stopped half a step later, as if her body had felt it before her mind decided to.',
    '“Did you—” Nela began.',
    '“Yes,” Astra said.',
    'Lumi didn’t speak right away. She looked down at the floor, then forward, then back again, as if comparing two versions of the same place.',
    '“This is the Portal Corridor,” she said quietly.',
    '“It is,” Astra replied, keeping her eyes on the space ahead. “But it’s not behaving the way it used to.”',
    'They stood at the edge of the corridor’s clean light, where everything always looked organised and safe, even when it had never fully been explainable. The Portal Corridor had always felt like it contained something hidden.',
    'Now it felt like it contained something active.',
    'Nela shifted her weight slightly. The corridor didn’t flicker or resist; the line of light on the floor moved a fraction to the left, as if making room.',
    'Nela froze. “Okay,” she whispered. “That was… polite.”',
    '“Or responsive,” Lumi said.',
    'Astra softened her focus the way she had learned to. She didn’t look at the wall or the floor, but at how the corridor connected to itself. Within that connection she noticed something faint in the air—not a symbol yet, not a pattern, but a suggestion of structure, like a sentence that hadn’t decided to become words.',
    '“It’s starting again,” Astra said.',
    'Lumi kept her notebook closed. She held it close but didn’t reach for it.',
    '“There’s a new condition,” Lumi murmured. “The environment is changing without the full symbol forming.”',
    'Nela’s voice came quieter than usual. “So what do we do?”',
    'Astra paused. She could feel the old instinct stirring—the urge to chase the shift, to force the moment to stay. But Part III had taught her something else.',
    'The system didn’t want to be taken. It wanted to be met.',
    '“We walk,” Astra said. “Slowly.”',
    '“Consistent pace,” Lumi added. “Consistent focus.”',
    'Nela lifted her hands slightly, like she was promising the corridor she wouldn’t do anything dramatic. “I can do consistent,” she said, then added, “for at least ten seconds.”',
    'They moved.',
    'One step. Then another.',
    'Astra watched the light. Lumi watched the edges. Nela watched both of them, learning the rhythm of the group itself.',
    'On the fifth step, the corridor changed again. Not visually this time. The sound of their footsteps didn’t arrive when it should have; the echo came back a fraction late, as if the space had briefly forgotten how far its walls were supposed to be.',
    'They all stopped.',
    '“That delay is increasing,” Lumi said.',
    '“It’s like the corridor is recalculating,” Astra replied.',
    '“Or choosing,” Nela said.',
    'Ahead of them, the corridor looked exactly the same. But Astra could feel a subtle split, as if there were two ways to continue even though there was still only one hallway.',
    'Her bracelet pulsed once—not bright or urgent, but directional.',
    'Astra didn’t point. She tilted her head slightly, changing her angle. A faint seam of light appeared along the wall, not drawn or marked, but present, like the corridor had a fold it had never shown before.',
    '“I see it,” Lumi said. There was no doubt in her voice.',
    'Nela took a careful half step forward, then stopped herself. “Tell me when,” she whispered.',
    '“This corridor has an activation zone,” Lumi said quietly.',
    '“You’re thinking of one that already exists,” Astra replied. “But we’re not there.”',
    '“Then why is it acting like we are?” Nela asked.',
    'Astra looked at the seam again. It wasn’t opening yet, but it was undeniably there.',
    '“Because we changed something,” she said.',
    'Lumi nodded. “We taught it that we can respond.”',
    'Nela stared at the line of light. “So now it’s responding first.”',
    'Astra felt the weight of that settle. Part III was over. They weren’t only discovering the system anymore.',
    'They had entered the phase where the system moved back.',
    'Astra stepped forward carefully toward the seam, without forcing it. The light brightened slightly. The space ahead didn’t become threatening or strange; it simply felt longer, like the corridor had unfolded one additional section of itself.',
    '“That’s impossible,” Lumi whispered automatically, then corrected herself. “That’s the point.”',
    'Nela let out a quiet sound that was half laugh, half awe. “It’s showing us a bigger version of itself.”',
    'Astra stayed still, listening to the sensation beneath the change. There was no danger in it, no pressure, but there was a question. Not a trap—a challenge.',
    '“Focus,” Astra said.',
    'Lumi nodded immediately. Nela’s posture shifted, becoming steadier.',
    'The seam held. The corridor stayed expanded.',
    'Then Astra blinked. For the briefest moment the seam flickered, not disappearing, only reminding her.',
    '“I get it,” Astra said softly. “If we lose focus, it won’t hold.”',
    '“So we don’t,” Nela said.',
    '“Together,” Lumi added.',
    'The corridor still looked the same—bright, quiet, ordinary. But it had depth now, and the depth had direction.',
    'Astra took another careful step forward.',
    'The corridor made room for it.'
  ];
  h.chapterBlock(16, 'The Corridor Changes', '🌙 first activation', ch16).forEach(b => c.push(b));

  // CH 17
  const ch17 = [
    'Astra didn’t move right away.',
    'The corridor had changed—not broken and not unstable, but different enough that standing still no longer felt neutral. It felt like letting something slip.',
    '“Don’t look away,” she said quietly.',
    'Lumi froze. “I wasn’t.”',
    'Nela blinked. “Was I about to?”',
    'Astra didn’t answer. She could feel it already. The faint seam of light they had followed was softer now, less defined. Not gone—just drifting.',
    '“It’s fading,” Astra whispered.',
    'Lumi stepped closer, careful not to break alignment. “No,” she said after a moment. “Not fading. Losing stability.”',
    '“It won’t stay if we don’t hold it,” Astra said.',
    '“Hold it how?” Nela frowned.',
    'Astra hesitated. This wasn’t the same as seeing, or understanding, or aligning. This was something new.',
    'She took a single step forward.',
    'The seam flickered and sharpened.',
    'Astra stopped. That was enough.',
    '“It responds to focus,” she said.',
    '“Consistent attention,” Lumi added. “Not just being here.”',
    '“So we’re not just standing,” Nela said slowly. “We’re keeping it in place.”',
    '“Yes.”',
    'After a moment, Nela said what all of them were thinking. “That feels harder.”',
    '“It is,” Lumi said. “Before, we noticed. Then we aligned. Now we maintain.”',
    'Maintain.',
    'Astra let the word settle. It didn’t mean forcing or correcting or reacting. It meant staying.',
    'She softened her focus again. The seam sharpened slightly.',
    'Then she blinked.',
    'The line slipped.',
    '“Wait—”',
    'Too late. The corridor shifted back, not fully, but enough that the seam loosened.',
    '“Did we lose it?” Nela asked.',
    '“No,” Lumi said. “We disrupted it.”',
    'Astra closed her eyes for a second—not frustrated, just resetting. When she opened them, she didn’t look directly at the seam. She let it come back to her.',
    'Slowly, it did.',
    'Faint. Weak. Waiting.',
    '“Okay,” Astra said. “We try again.”',
    'This time she didn’t step forward or adjust quickly. She didn’t chase clarity.',
    'She stayed.',
    'The seam stabilised.',
    'Lumi watched closely. “You didn’t correct it.”',
    '“I didn’t need to.”',
    'Nela leaned forward, then caught themselves. “Right. No sudden moves.”',
    'Astra almost smiled.',
    'The seam held, stronger now. Not because they did more, but because they did less.',
    '“It’s not about precision,” Lumi said quietly. “It’s about consistency.”',
    '“That I can do,” Nela said. After a beat, “I think.”',
    'They held their positions—not rigid or frozen, just aware.',
    'The corridor responded by staying.',
    'Before, everything appeared and vanished. Now, something remained.',
    '“It’s working,” Astra said.',
    'Lumi didn’t answer immediately. She was watching something deeper. “It’s stabilising.”',
    '“That sounds important,” Nela said.',
    '“It is,” Astra agreed.',
    'Because if they could hold it, they could move through it.',
    'Astra took a careful breath and extended her focus forward. Not stronger—just farther.',
    'The seam expanded. A second faint line appeared ahead, connected to the first.',
    'Nela’s eyes widened. “Okay. Now it’s definitely doing something.”',
    '“Progression,” Lumi said.',
    'Astra felt it too. This wasn’t a single moment anymore. It could continue.',
    '“As long as we don’t lose it,” she said.',
    '“I won’t,” Nela replied. No joke this time.',
    'They held it together. Time felt different here—steadier.',
    'Astra blinked.',
    'The second line flickered.',
    '“Stay with it,” Nela said, quick and calm.',
    'Astra stayed.',
    'The line returned, stronger.',
    '“That’s it,” Lumi said. “Shared focus increases stability.”',
    '“Yes,” Astra said.',
    'That was the rule now. Not seeing or understanding.',
    'Holding.',
    'The lines remained for one more moment, clear and connected. Then they softened—not disappearing, just settling back into the corridor.',
    '“That was harder than it looked,” Nela said.',
    '“It should be,” Lumi replied.',
    'Astra looked ahead. The corridor looked normal again, but she knew something new.',
    'Some things didn’t last. Others could—if you knew how to hold them.',
    '“We’re going to need this,” Astra said.',
    '“For what’s next,” Lumi agreed.',
    '“I think ‘next’ is getting closer,” Nela said.',
    'They didn’t move right away.',
    '“That was different,” Nela said.',
    '“Yes,” Astra replied.',
    '“We didn’t just find it,” Lumi added. “We kept it.”',
    'That mattered.',
    'Before, everything had been fragments. Now, something had remained—even if only briefly—because of them.',
    '“Okay,” Nela said. “That was kind of scary.”',
    '“Scary?” Lumi asked.',
    '“Not bad scary,” Nela said. “More like… if we mess it up, it disappears.”',
    'Astra sat beside them. “It didn’t disappear when we stayed together.”',
    '“That’s the part I like,” Nela said.',
    'Lumi remained standing for a moment, then sat too. “All systems that stabilise depend on consistency,” she said. After a pause, “and cooperation.”',
    'Nela smiled faintly. “That’s your way of saying we’ve got each other, right?”',
    'Lumi nodded. “…Yes.”',
    'Astra leaned back slightly. “I used to think the system was something outside us,” she said. “Something we only needed to understand.”',
    '“That was the model,” Lumi said.',
    '“I don’t think it is anymore.”',
    '“So what is it?” Nela asked.',
    'Astra answered carefully. “Something we’re part of.”',
    'Lumi didn’t correct her.',
    '“That means,” Nela said slowly, “if one of us slips—”',
    '“The whole thing feels it,” Astra finished.',
    '“And if one of us holds,” Lumi added, “the others don’t lose it.”',
    'They sat with that.',
    '“So we don’t just watch each other,” Astra said.',
    '“We keep each other steady,” Nela replied.',
    '“That increases stability,” Lumi said.',
    'Astra smiled a little. Nothing reacted. No symbol. No glow.',
    'But it mattered.',
    'After a moment, Astra stood. “We should keep going.”',
    'They stood together and started walking—not trying to make anything happen.',
    'Together.',
    'And somehow, that felt like the most important thing they’d learned so far.'
  ];
  h.chapterBlock(17, 'Focus', '🌙 second activation', ch17).forEach(b => c.push(b));

  // CH 18
  const ch18 = [
    'Astra knew it before she could explain it.',
    'The corridor hadn’t returned to normal. It only appeared to have. She stood still again, not because something was happening, but because something wasn’t showing itself.',
    '“That’s wrong,” she said quietly.',
    'Lumi looked up immediately. “What is?”',
    'Astra waited. That hesitation was becoming familiar now—the pause before understanding settled into words.',
    '“The corridor didn’t change back,” she said slowly.',
    'Nela frowned. “It looks the same.”',
    '“Yes,” Astra replied. “That’s the problem.”',
    'Lumi stepped forward—not into the corridor itself, but into the space between what she could see and what she expected. “What were we noticing before?” she asked.',
    '“Lines,” Astra said at once. “Connections. Depth.”',
    '“And now?” Lumi asked.',
    'Astra hesitated. “Nothing.” Then she corrected herself. “Not nothing. Just not visible.”',
    '“So it’s still there?” Nela asked.',
    'Astra looked ahead, adjusting her focus—not stronger, just differently. “Yes,” she said. “I just can’t see it anymore.”',
    'Lumi nodded slowly. “That means we’re missing a condition.”',
    '“What kind of condition?” Nela folded her arms.',
    'Lumi didn’t answer. For once, she didn’t fill the silence with a theory.',
    'Astra stepped forward.',
    'Nothing happened. No seam, no shift, no signal.',
    'Nela followed, with the same result. “Okay,” she said, “that’s officially less helpful than before.”',
    '“Wait,” Astra said.',
    'Lumi stopped immediately. “What?”',
    'Astra stayed where she was, but disengaged slightly—not stepping away, not leaving the space, simply releasing the effort to hold it.',
    'Something changed.',
    'Not in front of her, but around her. At the edge of her attention, something shifted—barely, but enough.',
    '“I saw it,” Astra whispered.',
    '“Where?” Lumi asked.',
    '“Not where I was looking,” Astra replied. “Next to it.”',
    'Lumi froze. Understanding arrived before explanation. “Peripheral perception,” she said quietly.',
    'Nela made a face. “That sounds important and complicated.”',
    '“Not complicated,” Astra said. “Just different.”',
    'She tried again, not focusing on the corridor directly. She let her attention widen, soften, lose the need to centre everything.',
    'The faintest trace returned. Not a line. Not a beam. A suggestion.',
    '“I see it again,” Astra said.',
    '“How?” Lumi asked.',
    '“I stopped trying to look at it.”',
    'Silence followed. That landed.',
    'Nela adjusted her stance slowly, testing the idea. “Wait,” she said. “I think I—” She stopped, then smiled slightly. “Yeah. Okay. That’s strange.”',
    '“That’s not visual dominance,” Lumi said. “It’s distributed awareness.”',
    'Nela blinked. “In normal words?”',
    '“You don’t look for it,” Lumi said. “You include it.”',
    'Astra nodded. “Yes.”',
    'Once all three of them adjusted in the same way, the corridor changed again. This time the structure didn’t appear in one place. It appeared in parts—edges, corners, in-between spaces. Not something to isolate, but something to notice all at once.',
    '“It isn’t meant to be seen directly,” Astra said. “It’s meant to be understood through everything else.”',
    '“That explains why we lost it when we focused too much,” Lumi said.',
    '“So we were looking too hard?” Nela asked.',
    '“Yes,” Astra replied. “For once.”',
    'Before, the challenge had been to notice more. Now, the challenge was to stop forcing clarity.',
    'Astra let her awareness settle into this new way of seeing. The corridor responded—not with a single symbol, but with layers. Faint, connected, everywhere.',
    'Lumi stepped forward carefully. The layers didn’t break.',
    'Nela followed. They didn’t disappear.',
    '“That’s new,” Nela said.',
    '“Yes,” Astra agreed. “This time it doesn’t need us to hold one point.”',
    '“We hold the whole,” Lumi said.',
    'That felt right.',
    'They walked forward together, not searching for a single signal. The corridor felt deeper now—not longer, but layered.',
    '“We’ve been seeing it wrong,” Astra said quietly.',
    '“Not wrong,” Lumi replied. “Just partially.”',
    'Nela grinned. “So this is the upgrade?”',
    '“Yes,” Astra said. “Now we see more.”',
    'They kept moving, not chasing or forcing anything, simply present.',
    'This time, the corridor didn’t wait for them to find it.',
    'It stayed.',
    'Because they had finally learned something deeper: not everything that matters is meant to be seen directly.',
    '“The system isn’t something we solve,” Lumi added.',
    '“It’s something we keep understanding,” Astra finished.',
    '“That never ends, does it?” Nela said.',
    'Astra looked ahead. For the first time, that didn’t feel overwhelming.',
    '“Good,” she said.',
    'They weren’t behind. They were exactly where they needed to be—knowing how to keep going.',
    'Together.'
  ];
  h.chapterBlock(18, 'Not Everything Is Visible', '🌙 third activation', ch18).forEach(b => c.push(b));

  // CH 19
  const ch19 = [
    'Astra felt it before she saw anything change.',
    'Not a line. Not a shift.',
    'A presence.',
    'The corridor no longer felt longer the way it had before. It felt deeper. They had been walking for some time now, carefully and consistently, holding awareness without narrowing it, letting everything exist at once.',
    'Nothing had changed—until it had.',
    '“Wait,” Astra said softly.',
    'Lumi stopped at once. Nela paused a moment later, not because she saw anything, but because she felt Astra slow.',
    '“What is it?” Nela asked.',
    'Astra didn’t answer immediately. She wasn’t focusing on a single place anymore. She was holding the edges, the space, the distance, the layers beneath what could be seen.',
    'And then she understood.',
    '“The corridor isn’t continuing,” she said.',
    'Lumi frowned slightly. “It looks like it is.”',
    'Astra shook her head. “Not in the same way.”',
    'Silence followed. Lumi adjusted her focus—not forward, but across the space. Between edges. Between expectations.',
    'Then she saw it.',
    'The corridor did not end, but it did not open either. There was a point of alignment so still, so precise, that it felt closed without being blocked.',
    '“That,” Lumi said slowly, “is not empty space.”',
    'Nela stared straight ahead. “I don’t see anything.”',
    'Astra nodded. “You won’t.”',
    'Nela sighed. “Helpful.”',
    'Astra stepped slightly aside and adjusted her angle. The space responded just enough to suggest shape, as if something invisible had edges.',
    'For a moment, an outline appeared—not a door and not a wall, but something between.',
    'A boundary.',
    '“…Okay,” Nela murmured. “That’s new.”',
    'Lumi stepped closer, careful. Her voice lowered. “That’s structured,” she said. “Not random.”',
    '“And it isn’t just there,” Astra added. “It’s waiting.”',
    'The word fit exactly.',
    'Nela looked between them. “So what do we do?”',
    'Astra hesitated. This was different. Before, they responded to the system. Now, something was expecting a response.',
    '“We don’t rush it,” Astra said.',
    'Lumi nodded. “Agreed.”',
    'Nela took a breath. “Okay. We don’t rush it.”',
    'They stood together facing the boundary—the place where the corridor stopped being just a corridor.',
    'Astra softened her focus, letting go of the urge to look directly. She let the structure exist within the whole of the space.',
    'The outline returned, stronger.',
    '“It’s holding,” Lumi said.',
    'Nela shifted her weight carefully. The boundary did not move, but something about it changed, as if registering them.',
    'Astra felt it immediately. “It’s aware of us.”',
    '“It reacts to input,” Lumi corrected gently.',
    '“Yes,” Astra said. “That.”',
    'They stayed aligned. No one stepped forward. No one forced the space to change.',
    'Slowly, the boundary began to unfold.',
    'Not opening. Revealing.',
    'A complex pattern spread across it, not like the symbols before, but denser, more connected—echoes of everything they had seen so far.',
    '“All of it?” Nela whispered.',
    '“No,” Lumi said. “The beginning.”',
    'Astra’s bracelet pulsed once—steady, unmistakable.',
    '“This is it,” Astra said.',
    'No one asked what she meant. They all knew.',
    'The system wasn’t just reacting anymore. It was offering something.',
    'Nela started to step forward, then stopped. “If we do this wrong… does it close?”',
    'Lumi hesitated. “Unknown.”',
    'Astra studied the structure carefully. It didn’t feel unstable or threatening.',
    '“No,” she said. “It doesn’t close. It waits.”',
    'That changed everything.',
    'Nela nodded slowly. “Then we don’t mess it up.”',
    '“We will,” Astra said gently. “We’re still learning.”',
    '“But we understand enough,” Lumi added.',
    'Astra looked at them, then forward. “Together.”',
    'She stepped ahead.',
    'The pattern responded—not resisting, not breaking.',
    'Accepting.',
    'Lumi stepped with her. Nela followed.',
    'The alignment completed.',
    'And for the first time, the space ahead didn’t just react.',
    'It opened.',
    'Not like a door, and not like a mechanism, but like a layer of reality easing aside just enough to show what was beyond.',
    'Astra caught her breath.',
    'Beyond it, the corridor continued—but changed. Brighter. Deeper. More possible.',
    '“This isn’t just another hallway,” Nela said.',
    '“It’s the first gate,” Lumi whispered.',
    'Astra nodded.',
    'Then she stepped through.',
    'She wouldn’t remember the light later. Or the opening.',
    'She would remember the decision.',
    'On the other side, the corridor looked similar at first—quiet, illuminated, ordinary—but the quiet felt different, thicker, as if the space held more than it showed.',
    'Lumi followed. Then Nela.',
    'Behind them, the space closed—not with sound or motion, but with a sensation, as if the previous corridor had gently let them go.',
    '“That’s closed,” Nela said quietly.',
    '“No visible return path,” Lumi confirmed.',
    'Astra didn’t turn back. Something ahead had already changed.',
    'This corridor did not feel continuous. It felt segmented, though there were no walls.',
    'Astra took one careful step. The ground remained the same, but the distance shifted. Her second step landed sooner than expected.',
    '“That’s inconsistent,” she said.',
    '“It isn’t linear,” Lumi replied.',
    '“Which means?” Nela asked.',
    '“It isn’t just a path anymore,” Astra said.',
    'Ahead, the space dimmed—not darker, just less certain. And then something appeared.',
    'A point.',
    'Unconnected. Isolated.',
    '“That’s new,” Astra whispered.',
    '“That’s not part of the previous pattern,” Lumi said.',
    '“So what is it?” Nela asked.',
    'Astra watched without forcing anything. For the first time since entering the system, she didn’t feel like she was following.',
    'She felt like she was being asked.',
    'She stepped toward the point.',
    'It didn’t move.',
    'It multiplied.',
    'A second point appeared. Then a third.',
    '“They aren’t reacting to position,” Lumi said.',
    '“Then what?” Nela asked.',
    '“…Choice,” Astra replied.',
    'The word remained, unfinished but heavy.',
    'She stopped.',
    'This time, she hesitated—not from fear, but from understanding.',
    '“This isn’t about perception anymore,” Lumi said quietly.',
    '“It’s something else,” Nela added.',
    'Astra looked back at them, then forward again.',
    '“We’re not just learning the system now,” she said. “We’re inside something that expects us to choose.”',
    'The points waited.',
    'And somewhere ahead, not yet visible, the next part of the world was already beginning to change.'
  ];
  h.chapterBlock(19, 'The First Gate', '🌙 fourth activation', ch19).forEach(b => c.push(b));

  // CH 20
  const ch20 = [
    'Astra didn’t realise she had been holding her breath until she let it go.',
    'The air on this side of the opening felt the same, and not the same at all. It was still a corridor, still bright, still quiet—but the quiet no longer felt incidental. It felt chosen, like a room that had not yet decided what it would become.',
    'Behind them, the space they had come from had settled. Not slammed closed and not locked—just finished, as if the corridor had turned a page and had no intention of rereading it.',
    'Nela turned first. “Okay,” she said softly. “That definitely closed.”',
    'Lumi didn’t argue. “No visible return path.”',
    'Astra didn’t look back. Not because she wasn’t curious, but because something ahead mattered more now.',
    'The corridor in front of them appeared continuous, but it didn’t behave that way. The air felt divided into sections without walls, as though distance itself had begun to behave differently.',
    'Astra took a careful step forward.',
    'Her foot landed sooner than her mind expected.',
    'She stopped immediately.',
    '“That’s not normal normal,” Nela whispered.',
    '“It’s not linear,” Lumi said, her gaze moving not forward but across the space—between edges, between distances, between what her eyes saw and what her understanding expected.',
    '“It’s not one path anymore,” Astra said.',
    'They stood with that. Not afraid. Just careful.',
    'Then Astra noticed it.',
    'A point, floating ahead—small, steady, unconnected. Like the first mark on a page before anything had been drawn around it.',
    'Her bracelet pulsed softly. Not a warning. Recognition.',
    '“That isn’t part of the earlier structure,” Lumi said.',
    '“So what is it?” Nela asked.',
    'Astra didn’t look at the point directly. She let her awareness include the corridor around it, the stillness behind it, the space beside it. The point didn’t flicker or hide.',
    'It waited.',
    '“It’s waiting,” Astra said.',
    '“For input,” Lumi replied, gently.',
    'Nela studied the space with unusual seriousness. “Okay. What kind of input?”',
    'Astra stepped forward again—slowly, deliberately.',
    'The point didn’t move.',
    'It multiplied.',
    'A second appeared. Then a third. Not connected, not forming a symbol—just increasing, as if responding not to movement, but to decision.',
    '“That isn’t reacting to position,” Lumi said quietly.',
    '“…Choice,” Astra finished.',
    'The word landed heavier than any rule before it. Not frightening, just demanding. This wasn’t the system reacting anymore. This was the system asking them to participate.',
    '“So what does it want us to choose?” Nela asked.',
    'Lumi didn’t rush to answer. “We observe first.”',
    '“Yes,” Astra said.',
    'The points remained. Four. Five. They didn’t feel threatening. They felt like options without labels.',
    'Lumi took one measured step forward. A new point appeared.',
    'Nela shifted her weight without stepping. Nothing changed.',
    '“Movement matters,” Astra observed.',
    '“But only when it’s intentional,” Lumi added.',
    '“So it counts when you mean it,” Nela said.',
    '“Yes,” Astra replied.',
    'The corridor adjusted subtly, as if agreeing.',
    'The points began to connect. Faint threads appeared between them—not a full structure, but the beginning of one.',
    '“It’s building something,” Astra whispered.',
    '“Only when we’re consistent,” Lumi replied.',
    'Nela stepped forward, carefully, deliberately. The threads held and strengthened.',
    '“That counts,” Nela said quietly.',
    '“Yes,” Astra agreed. “Because we’re doing it together.”',
    'Astra and Lumi stepped forward in sync—not copying, aligning. The threads brightened slightly, like a map becoming readable.',
    'They all stopped.',
    'Nothing disappeared.',
    'The structure stayed.',
    '“So this is… before,” Nela said.',
    '“The moment where we choose to continue,” Lumi added.',
    'Astra looked at them, not checking for certainty, but for alignment. She found it.',
    '“Now,” she said.',
    'They stepped forward at the same time—imperfectly, unrehearsed, but together.',
    'The threads completed themselves. The points resolved into something whole—not a door, not a symbol, but a structure that felt like permission.',
    'The corridor made room.',
    'They moved through.',
    'This time, Astra slowed instead of stopping.',
    'Behind them, the structure did not vanish.',
    '“It’s still there,” Lumi said.',
    'Astra glanced back slightly. The pattern they had formed remained—not frozen, but kept.',
    '“That didn’t happen before,” Nela said.',
    '“No,” Astra replied. “Before, everything disappeared.”',
    '“This corridor remembers,” Lumi said.',
    'That changed everything.',
    'Ahead of them, the space layered itself—faint variations of the corridor overlapping. Not separate paths, but possible ones.',
    '“I don’t think there’s just one way forward anymore,” Nela said.',
    '“Choice determines structure,” Lumi replied.',
    'Astra felt the weight of that settle—not fear, but responsibility. What they chose now would not vanish when they left. It would remain, shaping what came next.',
    '“This isn’t just the system anymore,” Astra said.',
    '“No,” Lumi agreed.',
    '“It’s becoming something,” Nela added.',
    'The space ahead held, waiting—not reacting instantly, but allowing the possibility to exist.',
    'For the first time, Astra didn’t feel like she was stepping into a mystery.',
    'She felt like she was stepping into something that would change because of them.',
    'And that meant whatever came next wouldn’t just be discovered.',
    'It would be shaped.'
  ];
  h.chapterBlock(20, 'Now', '🌙 fifth activation', ch20).forEach(b => c.push(b));

  return c;
}

function buildPart5() {
  const c = [];

  // PART V OPENER
  c.push(h.pageBreak());
  c.push(h.spacer(600));
  c.push(h.sectionTitle('🌙 PART V'));
  c.push(h.centeredText('REALISING', 36, true, '5A4A7A'));
  c.push(h.spacer(200));
  c.push(h.epigraph('The Academy doesn’t call out.'));
  c.push(h.epigraph('It simply waits for you to notice.'));
  c.push(h.pageBreak());

  // CH 21
  const ch21 = [
    'Astra didn’t step forward right away.',
    'Not because something stopped her, but because something settled.',
    'The space in front of them had already changed. Not suddenly and not dramatically, but completely. Behind them, the structure they had formed together remained—the threads, the points, the shape that had grown from their choices. It didn’t fade or reset. It stayed.',
    'Astra turned slightly, just enough to confirm it.',
    '“It’s still there,” she said.',
    '“Yes,” Lumi replied. After a brief pause, she added, “That means the system doesn’t reset anymore.”',
    'Nela folded her arms loosely. “So whatever we do…” She glanced between them. “…it stays?”',
    'Astra didn’t answer at once. That wasn’t a rule. It felt like something deeper.',
    'She looked forward instead. The corridor no longer felt like a passage. It felt arranged, not into sections or paths, but into meaning. Everything they had done up to this point seemed connected to where they were now.',
    '“It doesn’t feel like we just walked into something,” Astra said slowly.',
    'Lumi turned toward her. “What does it feel like?”',
    'Astra hesitated, then said, “Like we arrived.”',
    'The silence that followed was different. It settled rather than stretched.',
    '“…Arrived where?” Nela asked.',
    'Astra didn’t point. She didn’t have to. “Here.”',
    'Lumi’s expression shifted—not confusion, but recognition. “This is it,” she said quietly. “The structure we’ve been noticing.”',
    'She paused. “This is part of the Academy.”',
    'Nela looked around automatically. “But it’s still just a corridor.”',
    '“No,” Lumi said. “It just looks like one.”',
    'Astra nodded. For the first time, she understood what that meant. The corridor hadn’t turned into something else.',
    'They had.',
    'Now they could see what had always been there.',
    '“The Academy isn’t a place,” Astra said.',
    'Lumi met her gaze. “It’s a system.”',
    'The idea didn’t feel new, and that was what mattered. It felt familiar—like something they had always known, just without words.',
    '“So we didn’t find it,” Nela said.',
    '“No,” Astra replied. “We started noticing it.”',
    '“And then understanding it,” Lumi added.',
    '“And now we’re inside it,” Nela finished.',
    'Astra looked around again, not searching but recognising. The space felt intentional, coherent, held. Not random. Never random.',
    '“That means something else,” Astra said.',
    'Lumi nodded. “Yes.”',
    '“What?” Nela asked.',
    'Astra took a breath. “It means it was always here.”',
    'The silence that followed wasn’t heavy. It was clear.',
    '“The system didn’t appear when we noticed it,” Lumi said carefully. “We appeared inside it.”',
    'Nela let out a slow breath. “That’s bigger.”',
    '“Yes,” Astra agreed.',
    'Because this was no longer about uncovering something hidden. It was about understanding something that had never been missing—only unseen.',
    'Astra stepped forward.',
    'This time, the corridor didn’t respond. It didn’t need to.',
    'Their understanding had changed instead.',
    '“I don’t think the Academy is somewhere we go,” Astra said.',
    '“No,” Lumi replied. “It’s something we learn to see.”',
    '“That explains everything and nothing,” Nela said.',
    'Astra smiled softly. “Yes.”',
    'They stood there for another moment, not waiting and not testing. Just being there.',
    'For the first time, the space felt complete. Not finished, but whole.',
    '“We didn’t just get here,” Astra said after a moment. “We understand where we are.”',
    '“And what that means,” Lumi added.',
    '“And that we’re supposed to be here,” Nela said.',
    'Astra didn’t argue. It no longer felt like a question.',
    'The Academy didn’t open. It didn’t reveal itself or appear. It had always been present, folded into what looked ordinary, waiting for those who learned how to notice properly.',
    'And now they had.'
  ];
  h.chapterBlock(21, 'The Academy', '🌙 first realising', ch21).forEach(b => c.push(b));

  // CH 22
  const ch22 = [
    'Astra hadn’t expected it to feel so quiet.',
    'Not empty. Not finished.',
    'Clear.',
    'The space around them held steady. There were no shifting lines now, no forming symbols, no corrections. The system wasn’t hiding or testing. It was simply present, the way something is when it no longer needs to prove itself.',
    'Lumi stood beside her, not writing, not analysing. Just looking.',
    'That was new.',
    '“You’re not taking notes,” Astra said.',
    '“No,” Lumi replied. After a pause, “I don’t need to.”',
    'Nela sat on the floor nearby, cross-legged, watching the space with the kind of attention she usually reserved for things that were about to move.',
    '“It’s been here the whole time,” Nela said. Not a question.',
    '“Yes,” Astra replied.',
    '“And we just… couldn’t see it.”',
    '“We weren’t ready to,” Lumi said.',
    'Nela tilted her head. “Is that the same thing?”',
    'Lumi considered. “No,” she said finally. “It’s not.”',
    'Astra understood the difference. Not seeing something because it was hidden was one thing. Not seeing it because you hadn’t learned how to look was something else entirely.',
    '“The corridor,” Astra said slowly. “The shadow. The notebook. The symbol.” She paused. “All of it was already there.”',
    '“Waiting,” Nela said.',
    '“Not waiting,” Lumi corrected gently. “Existing. We’re the ones who were waiting.”',
    'That landed differently than Astra expected. She turned it over in her mind.',
    'They had spent so much time trying to find the system, to catch it, to understand it on their terms. But the system hadn’t been hiding. It had been consistent. Patient. Present.',
    'They were the ones who had needed to change.',
    '“I keep thinking about the first time,” Astra said. “The shadow that didn’t move.”',
    '“What about it?” Nela asked.',
    '“I thought something was wrong,” Astra said. “With the world. With the corridor.” She paused. “But nothing was wrong.”',
    '“Something was different,” Lumi said.',
    '“Yes.” Astra nodded. “And I didn’t know how to read it yet.”',
    'Nela looked at her. “And now?”',
    'Astra looked around the space—at the walls, the light, the air between things. Everything looked the same as it always had. And yet she could feel the structure beneath it, steady and coherent, the way a foundation feels when you finally understand what a building is standing on.',
    '“Now I know it was always there,” she said.',
    'The bracelet on her wrist didn’t pulse. It didn’t need to. It simply rested, warm and still, as if it had been waiting for this moment too.',
    '“Do you think other people can learn to see it?” Nela asked.',
    'Lumi answered first. “The system responds to attention and understanding. So yes.”',
    '“But not everyone will,” Astra added.',
    '“No,” Lumi agreed. “Not everyone will look.”',
    'Nela was quiet for a moment. “That’s kind of sad.”',
    '“Or kind of okay,” Astra said. “Everyone notices different things.”',
    'Nela smiled faintly. “That’s very diplomatic.”',
    '“It’s also true,” Lumi said.',
    'They stayed in the space a little longer. Not because they needed to, but because it felt right to let the moment exist without rushing past it.',
    'The system held around them, quiet and complete.',
    '“It was always there,” Astra said again, softer this time.',
    'Not as a discovery.',
    'As a fact she had finally made her own.'
  ];
  h.chapterBlock(22, 'It Was Always There', '🌙 second realising', ch22).forEach(b => c.push(b));

  // CH 23
  const ch23 = [
    'Astra didn’t say it out loud at first.',
    'She held it the way you hold something fragile—not tightly, just carefully, making sure it didn’t slip before she was ready.',
    'The space around them was still. Not empty still, but settled still, the kind that comes after something has been understood rather than before something is about to happen.',
    'Lumi was the one who said it.',
    '“We’re not imagining this.”',
    'Not as a question. Not as reassurance. As a statement of fact, delivered with the same precision she used for everything else.',
    'Nela looked at her. “Was that ever actually in question?”',
    '“For me,” Lumi said, “yes.”',
    'That surprised Astra. She turned to look at Lumi properly.',
    '“You doubted it?” she asked.',
    'Lumi was quiet for a moment. “I doubted the interpretation,” she said finally. “Not the observation. There’s a difference.”',
    'Astra understood. Lumi had never questioned what she saw. She had questioned what it meant.',
    '“And now?” Astra asked.',
    '“Now I have enough data,” Lumi said simply.',
    'Nela laughed—not unkindly. “Only you would call this data.”',
    '“What would you call it?” Lumi asked.',
    'Nela thought for a moment. “Proof,” she said.',
    'Lumi considered that. “That works too.”',
    'Astra looked between them. Something about the exchange felt important—not the words themselves, but the ease of them. They had started this as three people who noticed the same thing. Now they were three people who understood it together.',
    '“I used to wonder if I was making it up,” Astra said.',
    '“The shadow?” Nela asked.',
    '“All of it,” Astra said. “Every time it disappeared, I thought—maybe I just wanted to see something that wasn’t there.”',
    '“But it was there,” Lumi said.',
    '“Yes.”',
    '“And it still is,” Nela added.',
    'Astra nodded. The system hadn’t changed. It had never needed to. What had changed was her ability to hold it—to stay with it long enough to understand it rather than doubt it.',
    '“I think that’s the hardest part,” she said. “Not finding it. Trusting what you find.”',
    'Lumi was quiet for a moment. “That’s not a rule I wrote down,” she said.',
    '“No,” Astra agreed. “But it should be.”',
    'Nela stretched her arms above her head and looked up at the ceiling. “So what do we do with it?” she asked. “Now that we know it’s real.”',
    'Astra thought about that. It was a good question—maybe the most important one they’d asked.',
    '“We keep learning it,” she said.',
    '“And we don’t pretend we understand all of it,” Lumi added.',
    '“And we don’t stop,” Nela said.',
    'The three answers fit together the way their approaches always had—different, but aligned.',
    'The space around them held, quiet and present.',
    '“We’re not imagining this,” Astra said.',
    'Not as a conclusion.',
    'As a beginning.'
  ];
  h.chapterBlock(23, 'We’re Not Imagining This', '🌙 third realising', ch23).forEach(b => c.push(b));

  // CH 24
  const ch24 = [
    'Astra didn’t know exactly when the choice had been made.',
    'Not the moment they stepped through the gate, and not the moment the system first responded to all three of them together. It had been earlier than that—quieter, less dramatic.',
    'It had been the moment she decided to keep looking.',
    'She stood in the space now, the same corridor that had started everything, and it looked exactly as it always had. Pale walls. Polished stone. Late-afternoon light in long, soft bands.',
    'But she saw it differently.',
    'Not because the corridor had changed.',
    'Because she had chosen to.',
    '“This is where it started,” Nela said.',
    '“Yes,” Astra replied.',
    'Lumi looked around slowly, not searching for anything, just taking it in. “It looks the same.”',
    '“It is the same,” Astra said. “We’re not.”',
    'That settled between them without needing explanation.',
    'Nela crouched down and looked at the floor—at the place where the shadow had first stayed still, where everything had begun. “I wonder if it’s still doing it,” she said.',
    '“It is,” Astra said. “It never stopped.”',
    'Nela stood. “We just couldn’t see it.”',
    '“We chose not to,” Lumi said quietly. “Not consciously. But we weren’t ready.”',
    'Astra thought about that. There had been a version of her—not long ago—who had walked this corridor every day without noticing anything. Not because the system wasn’t there. Because she hadn’t been paying the right kind of attention.',
    '“What changed?” Nela asked.',
    'Astra considered the question carefully. “I stopped trying to explain it away,” she said. “The first time I saw the shadow, I told myself it was nothing. But I wrote it down anyway.”',
    '“That was the choice,” Lumi said.',
    '“Yes,” Astra agreed. “Not a big one. Just—deciding to take it seriously.”',
    'Nela smiled. “And then you found us.”',
    '“You found me,” Astra said to Lumi.',
    '“Nela found both of us,” Lumi replied.',
    '“The system found all of us,” Nela said.',
    'They stood with that for a moment.',
    '“I think that’s how it works,” Astra said. “You choose to see. And then you find the people who are also choosing.”',
    '“And together you see more,” Lumi added.',
    '“And then you can’t unsee it,” Nela finished.',
    'The corridor held around them, quiet and familiar and completely different from what it had been.',
    'Astra looked at the wall where the symbol had first appeared—faint, incomplete, gone before she could be sure of it. She could see it now, not with her eyes, but with the understanding she had built.',
    'It was still there.',
    'It had always been there.',
    '“We choose to see,” she said.',
    'Not as a declaration. Not as a conclusion.',
    'As a practice.',
    'Something they would keep doing—every day, in every corridor, in every moment that looked ordinary but wasn’t.',
    'The bracelet on her wrist rested warm and still.',
    'The system held, patient and present.',
    'And somewhere ahead, the Academy waited—not for them to arrive, but for them to keep noticing.',
    'They already were.'
  ];
  h.chapterBlock(24, 'We Choose to See', '🌙 fourth realising', ch24).forEach(b => c.push(b));

  return c;
}

module.exports = { buildPart4, buildPart5 };